// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The rpki-selflab authors
// ============================================================================
// Service URLs, and the per-component content of the side panel: full
// sentences, one complete copy per language (rather than field-by-field
// dictionaries), since it reads better as connected prose in each language.
// ============================================================================

// Every link points at the host the panel was opened from. Opened as
// localhost, each web app is reached through the panel's own port under
// <name>.localhost (nginx routes by name). Opened by IP or another name,
// those names don't resolve, so fall back to each service's own port, which
// only answers when lab.conf has EXPOSE_PORTS=yes.
const HOST = location.hostname;
const VHOST = HOST === "localhost";
const PANEL_PORT = location.port ? `:${location.port}` : "";
const svcUrl = (name, scheme, port) =>
  VHOST ? `http://${name}.localhost${PANEL_PORT}` : `${scheme}://${HOST}:${port}`;
const TTYD_URL       = svcUrl("console", "http", 7681);
const KRILL_URL      = svcUrl("krill", "https", 3000);
const ROUTINATOR_URL = svcUrl("routinator", "http", 8323);
const REGISTRY_URL   = svcUrl("registry", "http", 8081);
const REGISTRO_BR_URL = "https://beta.registro.br/login/";

// edit: the file a student would copy into work/ to experiment, and the
// command that loads their copy on the router.
const EDIT = {
  birdNode: (node, file) => ({
    file,
    copy: `cp ${file} work/my-${node}.conf`,
    load: `docker exec lab-${node} birdc 'configure "/etc/lab-work/my-${node}.conf"'`,
  }),
  observer2: {
    file: "openbgpd/observer2-none.conf",
    copy: "cp openbgpd/observer2-none.conf work/my-observer2.conf",
    load: "docker exec lab-observer2 sh -c 'cp /etc/lab-work/my-observer2.conf /etc/bgpd.conf && bgpctl reload'",
  },
  observer3: {
    file: "openbgpd/observer3-none.conf",
    copy: "cp openbgpd/observer3-none.conf work/my-observer3.conf",
    load: "docker exec lab-observer3 sh -c 'cp /etc/lab-work/my-observer3.conf /etc/bgpd.conf && bgpctl reload'",
  },
};

const NODES = {
  en: {
    krill: {
      name: "Krill",
      role: "Your CA. This is where you create the ROAs and the ASPA object, through the web UI (ROAs and ASPAs tabs) or with krillc in its terminal.",
      info: { "Image": "rpki-selflab/krill (Krill 0.16.0)", "Web UI": KRILL_URL, "Token": "labpass", "CA name": "acme_ca" },
      web: ["krill", "Krill"],
      term: [["Terminal (krillc)", "krill"]],
      hint: 'krillc show\nkrillc roas list\nkrillc aspas list\nkrillc aspas add --aspa "AS64500 => AS64501"',
    },
    routinator: {
      name: "Routinator — observer1's validator",
      role: "Validates the objects published under the lab's TA and hands ROAs and ASPAs to observer1 over the RTR protocol.",
      info: { "Image": "rpki-selflab/routinator (Routinator 0.15.2)", "Web UI": ROUTINATOR_URL, "RTR": "172.30.0.20:3323",
              "Flags": "--no-rir-tals --extra-tals-dir=/tals --enable-aspa" },
      web: ["routinator", "Routinator"],
      links: [["Status (text)", "/api/routinator/status"], ["JSON output", "/api/routinator/json"]],
      term: [["Terminal", "routinator"]],
      hint: "routinator --no-rir-tals --extra-tals-dir=/tals --enable-aspa vrps",
    },
    fort: {
      name: "FORT Validator — observer3's validator",
      role: "Another validator. Same job as Routinator, different implementation, feeding observer3 over RTR. It has no web UI.",
      info: { "Image": "rpki-selflab/fort (built from source)", "Version": "1.7.0.experimental",
              "RTR": "172.30.0.50:3323", "Why that version": "ASPA and RTR v2 only exist from it onwards",
              "Flags": "--server.max-rtr-version=2 --rsync.enabled=false" },
      term: [["Terminal", "fort"]],
      hint: "cat /var/lib/fort/vrps.json\ncat /var/lib/fort/aspas.json",
    },
    attacker: {
      name: "attacker — AS666",
      role: "A hijacker that is a customer of the three observers: it opens sessions straight to them and announces the origin's prefixes. Silent until the guide turns it on.",
      info: { "ASN": "666 (not a reserved ASN; harmless, this network is isolated)",
              "Towards observer1": "10.200.7.10 / fd00:7::10", "Towards observer2": "10.200.13.10 / fd00:13::10",
              "Towards observer3": "10.200.8.10 / fd00:8::10",
              "Configs": "bird/attacker-off.conf, -simple.conf, -posrov.conf" },
      term: [["Terminal (birdc)", "attacker", "birdc"], ["Shell", "attacker"]],
      hint: "show protocols\nshow route export observer1_v4",
      edit: EDIT.birdNode("attacker", "bird/attacker-posrov.conf"),
    },
    peer: {
      name: "peer — AS64499",
      role: "A legitimate network that peers privately with the origin and buys transit from Provider A. Normally it keeps what it learns from the origin to itself; when the guide switches the leak on, it passes those routes on to Provider A.",
      info: { "ASN": "64499 (documentation ASN, RFC 5398)",
              "Peering with origin": "10.200.9.10 / fd00:9::10", "Transit from Provider A": "10.200.10.10 / fd00:10::10",
              "Configs": "bird/peer-off.conf, peer-leak.conf" },
      term: [["Terminal (birdc)", "peer", "birdc"], ["Shell", "peer"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("peer", "bird/peer-off.conf"),
    },
    origin: {
      name: "origin — AS64500",
      role: "Your AS. Originates 203.0.113.0/24 and 3fff:cafe::/32 and is multihomed to Providers A and B. It prefers B: the announcement to A is prepended twice.",
      info: { "ASN": "64500", "IPv4": "203.0.113.0/24", "IPv6": "3fff:cafe::/32",
              "Link A": "10.200.1.10 / fd00:1::10", "Link B": "10.200.2.10 / fd00:2::10", "Config": "bird/origin.conf" },
      term: [["Terminal (birdc)", "origin", "birdc"], ["Shell", "origin"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("origin", "bird/origin.conf"),
    },
    "provider-a": {
      name: "Provider A — AS64501",
      role: "The origin's backup upstream (the origin prepends twice when announcing to it). Passes the prefix on to ALL THREE observers and, once the peer starts leaking, passes on the leaked path instead of its own, because the peer's path is shorter than the origin's prepended one.",
      info: { "ASN": "64501 (RFC 5398)", "Towards origin": "10.200.1.20 / fd00:1::20",
              "Towards observer1": "10.200.3.10 / fd00:3::10", "Towards observer2": "10.200.11.10 / fd00:11::10",
              "Towards observer3": "10.200.5.10 / fd00:5::10",
              "Config": "bird/provider-a.conf" },
      term: [["Terminal (birdc)", "provider-a", "birdc"], ["Shell", "provider-a"]],
      hint: "show route\nshow protocols all observer1_v4",
      edit: EDIT.birdNode("provider-a", "bird/provider-a.conf"),
    },
    "provider-b": {
      name: "Provider B — AS64502",
      role: "The origin's preferred upstream. Passes the prefix on to all three observers. If the origin's ASPA object doesn't list it, the observers mark the path through here ASPA Invalid.",
      info: { "ASN": "64502 (RFC 5398)", "Towards origin": "10.200.2.20 / fd00:2::20",
              "Towards observer1": "10.200.4.10 / fd00:4::10", "Towards observer2": "10.200.12.10 / fd00:12::10",
              "Towards observer3": "10.200.6.10 / fd00:6::10",
              "Config": "bird/provider-b.conf" },
      term: [["Terminal (birdc)", "provider-b", "birdc"], ["Shell", "provider-b"]],
      hint: "show route",
      edit: EDIT.birdNode("provider-b", "bird/provider-b.conf"),
    },
    observer1: {
      name: "observer1 — AS64509 (BIRD)",
      role: "Receives the same prefix over both paths and applies ROV (RFC 6811) and ASPA (upstream algorithm) in its import filter. BIRD has no per-route validation attribute, so the verdict is recorded in large communities.",
      info: { "ASN": "64509 (RFC 5398)", "Validator": "Routinator (172.30.0.20:3323)",
              "From Provider A": "10.200.3.20 / fd00:3::20", "From Provider B": "10.200.4.20 / fd00:4::20",
              "Config": "bird/observer1-<stage>.conf" },
      term: [["Terminal (birdc)", "observer1", "birdc"], ["Shell", "observer1"]],
      hint: "show route table master4 all\nshow protocols all routinator\nshow route table aspa_table",
      edit: EDIT.birdNode("observer1", "bird/observer1-none.conf"),
    },
    observer2: {
      name: "observer2 — AS64510 (OpenBGPD + rpki-client)",
      role: "Router and validator on the same host. rpki-client fetches the repository itself and writes the validated ROAs and ASPAs into a file (roa-set and aspa-set) that bgpd includes; a periodic job runs it again and reloads bgpd. No RTR session and no separate validator: the way OpenBSD does it.",
      info: { "ASN": "64510 (RFC 5398)", "Validator": "rpki-client 9.5, same host (every 2 minutes and on every step command)",
              "File included": "/var/db/rpki-client/openbgpd", "Image": "OpenBGPD 8.8 + rpki-client 9.5 (Alpine 3.22)",
              "From Provider A": "10.200.11.20 / fd00:11::20", "From Provider B": "10.200.12.20 / fd00:12::20",
              "RFC 9234 role": "provider (selects the upstream algorithm)", "Config": "openbgpd/observer2-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer2", "bgpctl"], ["Shell", "observer2"]],
      hint: "bgpctl show sets\nbgpctl show rib detail\ncat /var/db/rpki-client/openbgpd\nrpki-refresh",
      edit: EDIT.observer2,
    },
    observer3: {
      name: "observer3 — AS64511 (OpenBGPD + FORT)",
      role: "Another opinion: same prefix, same paths, a different router and a different validator, which hands over its data over RTR. OpenBGPD computes the verdicts natively into the ovs and avs fields, with no community convention needed.",
      info: { "ASN": "64511 (RFC 5398)", "Validator": "FORT (172.30.0.50:3323)", "Image": "OpenBGPD 8.8 (Alpine 3.22)",
              "From Provider A": "10.200.5.20 / fd00:5::20", "From Provider B": "10.200.6.20 / fd00:6::20",
              "RFC 9234 role": "provider (selects the upstream algorithm)", "Config": "openbgpd/observer3-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer3", "bgpctl"], ["Shell", "observer3"]],
      hint: "bgpctl show rib detail\nbgpctl show rtr\nbgpctl show sets",
      edit: EDIT.observer3,
    },
    registry_local: {
      role: "The simulated RIR/NIR that runs inside the lab. It issues the certificate for the allocated resources and hosts the repository. No Internet, no credentials.",
      info: { "Mode": "local (self-contained)", "Registry panel": REGISTRY_URL,
              "Trust anchor": "generated by the lab itself", "Publication": "RRDP at https://rir.lab:3000/rrdp/" },
      hint: "krillc list\nkrillc children connections --ca testbed\nkrillc pubserver publishers list",
    },
    registry_beta: {
      role: "Registro.br's test system: trust anchor, parent CA for your AS, and remote publication server. Needs Internet and a beta.registro.br login.",
      info: { "Mode": "beta (Registro.br)", "TAL": "https://rpki-test-ta.beta.registro.br/ta/ta.tal", "Panel": REGISTRO_BR_URL },
    },
  },
  es: {
    krill: {
      name: "Krill",
      role: "Su CA. Aquí se crean las ROAs y el objeto ASPA, por la interfaz web (pestañas ROAs y ASPAs) o con krillc en su terminal.",
      info: { "Imagen": "rpki-selflab/krill (Krill 0.16.0)", "Interfaz web": KRILL_URL, "Token": "labpass", "Nombre de la CA": "acme_ca" },
      web: ["krill", "Krill"],
      term: [["Terminal (krillc)", "krill"]],
      hint: 'krillc show\nkrillc roas list\nkrillc aspas list\nkrillc aspas add --aspa "AS64500 => AS64501"',
    },
    routinator: {
      name: "Routinator — validador del observer1",
      role: "Valida los objetos publicados bajo la TA del laboratorio y entrega ROAs y ASPAs al observer1 por el protocolo RTR.",
      info: { "Imagen": "rpki-selflab/routinator (Routinator 0.15.2)", "Interfaz web": ROUTINATOR_URL, "RTR": "172.30.0.20:3323",
              "Flags": "--no-rir-tals --extra-tals-dir=/tals --enable-aspa" },
      web: ["routinator", "Routinator"],
      links: [["Estado (texto)", "/api/routinator/status"], ["Salida JSON", "/api/routinator/json"]],
      term: [["Terminal", "routinator"]],
      hint: "routinator --no-rir-tals --extra-tals-dir=/tals --enable-aspa vrps",
    },
    fort: {
      name: "FORT Validator — validador del observer3",
      role: "Otro validador. Hace el mismo trabajo que Routinator, con otra implementación, y alimenta al observer3 por RTR. No tiene interfaz web.",
      info: { "Imagen": "rpki-selflab/fort (compilada desde el código fuente)", "Versión": "1.7.0.experimental",
              "RTR": "172.30.0.50:3323", "Por qué esa versión": "ASPA y RTR v2 existen solo a partir de ella",
              "Flags": "--server.max-rtr-version=2 --rsync.enabled=false" },
      term: [["Terminal", "fort"]],
      hint: "cat /var/lib/fort/vrps.json\ncat /var/lib/fort/aspas.json",
    },
    attacker: {
      name: "atacante — AS666",
      role: "Un secuestrador que es cliente de los tres observadores: abre sesiones directas con ellos y anuncia los prefijos del origen. Está callado hasta que la guía lo activa.",
      info: { "ASN": "666 (no es un ASN reservado; es inofensivo, esta red está aislada)",
              "Hacia observer1": "10.200.7.10 / fd00:7::10", "Hacia observer2": "10.200.13.10 / fd00:13::10",
              "Hacia observer3": "10.200.8.10 / fd00:8::10",
              "Configs": "bird/attacker-off.conf, -simple.conf, -posrov.conf" },
      term: [["Terminal (birdc)", "attacker", "birdc"], ["Shell", "attacker"]],
      hint: "show protocols\nshow route export observer1_v4",
      edit: EDIT.birdNode("attacker", "bird/attacker-posrov.conf"),
    },
    peer: {
      name: "peer — AS64499",
      role: "Una red legítima que hace peering privado con el origen y compra tránsito al Proveedor A. Normalmente se guarda lo que aprende del origen; cuando la guía activa la fuga, pasa esas rutas al Proveedor A.",
      info: { "ASN": "64499 (ASN de documentación, RFC 5398)",
              "Peering con el origen": "10.200.9.10 / fd00:9::10", "Tránsito del Proveedor A": "10.200.10.10 / fd00:10::10",
              "Configs": "bird/peer-off.conf, peer-leak.conf" },
      term: [["Terminal (birdc)", "peer", "birdc"], ["Shell", "peer"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("peer", "bird/peer-off.conf"),
    },
    origin: {
      name: "origen — AS64500",
      role: "Su AS. Origina 203.0.113.0/24 y 3fff:cafe::/32 y tiene dos proveedores, A y B. Prefiere B: el anuncio hacia A lleva el ASN repetido dos veces más (prepend).",
      info: { "ASN": "64500", "IPv4": "203.0.113.0/24", "IPv6": "3fff:cafe::/32",
              "Enlace A": "10.200.1.10 / fd00:1::10", "Enlace B": "10.200.2.10 / fd00:2::10", "Config": "bird/origin.conf" },
      term: [["Terminal (birdc)", "origin", "birdc"], ["Shell", "origin"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("origin", "bird/origin.conf"),
    },
    "provider-a": {
      name: "Proveedor A — AS64501",
      role: "El upstream de respaldo del origen (el origen hace prepend dos veces al anunciarle). Entrega el prefijo a LOS TRES observadores y, cuando el peer empieza a filtrar, pasa el camino filtrado en lugar del suyo, porque el camino del peer es más corto que el del origen con prepend.",
      info: { "ASN": "64501 (RFC 5398)", "Hacia el origen": "10.200.1.20 / fd00:1::20",
              "Hacia observer1": "10.200.3.10 / fd00:3::10", "Hacia observer2": "10.200.11.10 / fd00:11::10",
              "Hacia observer3": "10.200.5.10 / fd00:5::10",
              "Config": "bird/provider-a.conf" },
      term: [["Terminal (birdc)", "provider-a", "birdc"], ["Shell", "provider-a"]],
      hint: "show route\nshow protocols all observer1_v4",
      edit: EDIT.birdNode("provider-a", "bird/provider-a.conf"),
    },
    "provider-b": {
      name: "Proveedor B — AS64502",
      role: "El upstream preferido del origen. Entrega el prefijo a los tres observadores. Si el objeto ASPA del origen no lo incluye, los observadores marcan como ASPA Invalid el camino que pasa por aquí.",
      info: { "ASN": "64502 (RFC 5398)", "Hacia el origen": "10.200.2.20 / fd00:2::20",
              "Hacia observer1": "10.200.4.10 / fd00:4::10", "Hacia observer2": "10.200.12.10 / fd00:12::10",
              "Hacia observer3": "10.200.6.10 / fd00:6::10",
              "Config": "bird/provider-b.conf" },
      term: [["Terminal (birdc)", "provider-b", "birdc"], ["Shell", "provider-b"]],
      hint: "show route",
      edit: EDIT.birdNode("provider-b", "bird/provider-b.conf"),
    },
    observer1: {
      name: "observador 1 — AS64509 (BIRD)",
      role: "Recibe el mismo prefijo por los dos caminos y aplica ROV (RFC 6811) y ASPA (algoritmo upstream) en su filtro de importación. BIRD no tiene un atributo de validación por ruta, así que el veredicto se guarda en large communities.",
      info: { "ASN": "64509 (RFC 5398)", "Validador": "Routinator (172.30.0.20:3323)",
              "Desde Proveedor A": "10.200.3.20 / fd00:3::20", "Desde Proveedor B": "10.200.4.20 / fd00:4::20",
              "Config": "bird/observer1-<stage>.conf" },
      term: [["Terminal (birdc)", "observer1", "birdc"], ["Shell", "observer1"]],
      hint: "show route table master4 all\nshow protocols all routinator\nshow route table aspa_table",
      edit: EDIT.birdNode("observer1", "bird/observer1-none.conf"),
    },
    observer2: {
      name: "observador 2 — AS64510 (OpenBGPD + rpki-client)",
      role: "Router y validador en el mismo host. rpki-client descarga el repositorio él mismo y escribe las ROAs y los ASPAs validados en un archivo (roa-set y aspa-set) que bgpd incluye; una tarea periódica lo vuelve a ejecutar y recarga bgpd. Sin sesión RTR y sin validador aparte: es como lo hace OpenBSD.",
      info: { "ASN": "64510 (RFC 5398)", "Validador": "rpki-client 9.5, mismo host (cada 2 minutos y en cada comando de paso)",
              "Archivo incluido": "/var/db/rpki-client/openbgpd", "Imagen": "OpenBGPD 8.8 + rpki-client 9.5 (Alpine 3.22)",
              "Desde Proveedor A": "10.200.11.20 / fd00:11::20", "Desde Proveedor B": "10.200.12.20 / fd00:12::20",
              "Rol RFC 9234": "provider (selecciona el algoritmo upstream)", "Config": "openbgpd/observer2-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer2", "bgpctl"], ["Shell", "observer2"]],
      hint: "bgpctl show sets\nbgpctl show rib detail\ncat /var/db/rpki-client/openbgpd\nrpki-refresh",
      edit: EDIT.observer2,
    },
    observer3: {
      name: "observador 3 — AS64511 (OpenBGPD + FORT)",
      role: "Otra opinión: mismo prefijo, mismos caminos, otro router y otro validador, que le entrega los datos por RTR. OpenBGPD calcula los veredictos de forma nativa en los campos ovs y avs, sin necesidad de communities.",
      info: { "ASN": "64511 (RFC 5398)", "Validador": "FORT (172.30.0.50:3323)", "Imagen": "OpenBGPD 8.8 (Alpine 3.22)",
              "Desde Proveedor A": "10.200.5.20 / fd00:5::20", "Desde Proveedor B": "10.200.6.20 / fd00:6::20",
              "Rol RFC 9234": "provider (selecciona el algoritmo upstream)", "Config": "openbgpd/observer3-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer3", "bgpctl"], ["Shell", "observer3"]],
      hint: "bgpctl show rib detail\nbgpctl show rtr\nbgpctl show sets",
      edit: EDIT.observer3,
    },
    registry_local: {
      role: "El RIR/NIR simulado que corre dentro del laboratorio. Emite el certificado de los recursos asignados y aloja el repositorio. Sin Internet, sin credenciales.",
      info: { "Modo": "local (autocontenido)", "Panel del registro": REGISTRY_URL,
              "Ancla de confianza": "generada por el propio laboratorio", "Publicación": "RRDP en https://rir.lab:3000/rrdp/" },
      hint: "krillc list\nkrillc children connections --ca testbed\nkrillc pubserver publishers list",
    },
    registry_beta: {
      role: "El sistema de pruebas de Registro.br: ancla de confianza, CA padre de su AS y servidor de publicación remota. Necesita Internet y un usuario en beta.registro.br.",
      info: { "Modo": "beta (Registro.br)", "TAL": "https://rpki-test-ta.beta.registro.br/ta/ta.tal", "Panel": REGISTRO_BR_URL },
    },
  },
  pt: {
    krill: {
      name: "Krill",
      role: "A sua CA. É aqui que você cria as ROAs e o objeto ASPA, pela interface web (abas ROAs e ASPAs) ou com o krillc no terminal dele.",
      info: { "Imagem": "rpki-selflab/krill (Krill 0.16.0)", "Interface web": KRILL_URL, "Token": "labpass", "Nome da CA": "acme_ca" },
      web: ["krill", "Krill"],
      term: [["Terminal (krillc)", "krill"]],
      hint: 'krillc show\nkrillc roas list\nkrillc aspas list\nkrillc aspas add --aspa "AS64500 => AS64501"',
    },
    routinator: {
      name: "Routinator — validador do observer1",
      role: "Valida os objetos publicados sob a TA do laboratório e entrega ROAs e ASPAs ao observer1 pelo protocolo RTR.",
      info: { "Imagem": "rpki-selflab/routinator (Routinator 0.15.2)", "Interface web": ROUTINATOR_URL, "RTR": "172.30.0.20:3323",
              "Flags": "--no-rir-tals --extra-tals-dir=/tals --enable-aspa" },
      web: ["routinator", "Routinator"],
      links: [["Status (texto)", "/api/routinator/status"], ["Saída JSON", "/api/routinator/json"]],
      term: [["Terminal", "routinator"]],
      hint: "routinator --no-rir-tals --extra-tals-dir=/tals --enable-aspa vrps",
    },
    fort: {
      name: "FORT Validator — validador do observer3",
      role: "Outro validador. Faz o mesmo trabalho do Routinator, com outra implementação, e alimenta o observer3 pelo RTR. Não tem interface web.",
      info: { "Imagem": "rpki-selflab/fort (compilada a partir do código-fonte)", "Versão": "1.7.0.experimental",
              "RTR": "172.30.0.50:3323", "Por que essa versão": "ASPA e RTR v2 só existem a partir dela",
              "Flags": "--server.max-rtr-version=2 --rsync.enabled=false" },
      term: [["Terminal", "fort"]],
      hint: "cat /var/lib/fort/vrps.json\ncat /var/lib/fort/aspas.json",
    },
    attacker: {
      name: "atacante — AS666",
      role: "Um sequestrador que é cliente dos três observadores: abre sessões direto com eles e anuncia os prefixos da origem. Fica calado até o roteiro ligá-lo.",
      info: { "ASN": "666 (não é um ASN reservado; é inofensivo, esta rede é isolada)",
              "Para observer1": "10.200.7.10 / fd00:7::10", "Para observer2": "10.200.13.10 / fd00:13::10",
              "Para observer3": "10.200.8.10 / fd00:8::10",
              "Configs": "bird/attacker-off.conf, -simple.conf, -posrov.conf" },
      term: [["Terminal (birdc)", "attacker", "birdc"], ["Shell", "attacker"]],
      hint: "show protocols\nshow route export observer1_v4",
      edit: EDIT.birdNode("attacker", "bird/attacker-posrov.conf"),
    },
    peer: {
      name: "peer — AS64499",
      role: "Uma rede legítima que faz peering privado com a origem e compra trânsito do Provedor A. Normalmente guarda para si o que aprende da origem; quando o roteiro liga o vazamento, repassa essas rotas ao Provedor A.",
      info: { "ASN": "64499 (ASN de documentação, RFC 5398)",
              "Peering com a origem": "10.200.9.10 / fd00:9::10", "Trânsito do Provedor A": "10.200.10.10 / fd00:10::10",
              "Configs": "bird/peer-off.conf, peer-leak.conf" },
      term: [["Terminal (birdc)", "peer", "birdc"], ["Shell", "peer"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("peer", "bird/peer-off.conf"),
    },
    origin: {
      name: "origem — AS64500",
      role: "O seu AS. Origina 203.0.113.0/24 e 3fff:cafe::/32 e tem dois provedores, A e B. Prefere o B: o anúncio para o A leva o ASN repetido mais duas vezes (prepend).",
      info: { "ASN": "64500", "IPv4": "203.0.113.0/24", "IPv6": "3fff:cafe::/32",
              "Enlace A": "10.200.1.10 / fd00:1::10", "Enlace B": "10.200.2.10 / fd00:2::10", "Config": "bird/origin.conf" },
      term: [["Terminal (birdc)", "origin", "birdc"], ["Shell", "origin"]],
      hint: "show protocols\nshow route export provider_a_v4",
      edit: EDIT.birdNode("origin", "bird/origin.conf"),
    },
    "provider-a": {
      name: "Provedor A — AS64501",
      role: "O upstream de reserva da origem (a origem faz prepend duas vezes ao anunciar para ele). Entrega o prefixo aos TRÊS observadores e, quando o peer começa a vazar, repassa o caminho vazado no lugar do seu, porque o caminho do peer é mais curto que o da origem com prepend.",
      info: { "ASN": "64501 (RFC 5398)", "Para a origem": "10.200.1.20 / fd00:1::20",
              "Para observer1": "10.200.3.10 / fd00:3::10", "Para observer2": "10.200.11.10 / fd00:11::10",
              "Para observer3": "10.200.5.10 / fd00:5::10",
              "Config": "bird/provider-a.conf" },
      term: [["Terminal (birdc)", "provider-a", "birdc"], ["Shell", "provider-a"]],
      hint: "show route\nshow protocols all observer1_v4",
      edit: EDIT.birdNode("provider-a", "bird/provider-a.conf"),
    },
    "provider-b": {
      name: "Provedor B — AS64502",
      role: "O upstream preferido da origem. Entrega o prefixo aos três observadores. Se o objeto ASPA da origem não o incluir, os observadores marcam como ASPA Invalid o caminho que passa por aqui.",
      info: { "ASN": "64502 (RFC 5398)", "Para a origem": "10.200.2.20 / fd00:2::20",
              "Para observer1": "10.200.4.10 / fd00:4::10", "Para observer2": "10.200.12.10 / fd00:12::10",
              "Para observer3": "10.200.6.10 / fd00:6::10",
              "Config": "bird/provider-b.conf" },
      term: [["Terminal (birdc)", "provider-b", "birdc"], ["Shell", "provider-b"]],
      hint: "show route",
      edit: EDIT.birdNode("provider-b", "bird/provider-b.conf"),
    },
    observer1: {
      name: "observador 1 — AS64509 (BIRD)",
      role: "Recebe o mesmo prefixo pelos dois caminhos e aplica ROV (RFC 6811) e ASPA (algoritmo upstream) no filtro de importação. O BIRD não tem atributo de validação por rota, então o veredito é gravado em large communities.",
      info: { "ASN": "64509 (RFC 5398)", "Validador": "Routinator (172.30.0.20:3323)",
              "Do Provedor A": "10.200.3.20 / fd00:3::20", "Do Provedor B": "10.200.4.20 / fd00:4::20",
              "Config": "bird/observer1-<stage>.conf" },
      term: [["Terminal (birdc)", "observer1", "birdc"], ["Shell", "observer1"]],
      hint: "show route table master4 all\nshow protocols all routinator\nshow route table aspa_table",
      edit: EDIT.birdNode("observer1", "bird/observer1-none.conf"),
    },
    observer2: {
      name: "observador 2 — AS64510 (OpenBGPD + rpki-client)",
      role: "Roteador e validador no mesmo host. O rpki-client baixa o repositório ele mesmo e grava as ROAs e os ASPAs validados num arquivo (roa-set e aspa-set) que o bgpd inclui; uma tarefa periódica roda de novo e recarrega o bgpd. Sem sessão RTR e sem validador separado: é como o OpenBSD faz.",
      info: { "ASN": "64510 (RFC 5398)", "Validador": "rpki-client 9.5, mesmo host (a cada 2 minutos e em cada comando de passo)",
              "Arquivo incluído": "/var/db/rpki-client/openbgpd", "Imagem": "OpenBGPD 8.8 + rpki-client 9.5 (Alpine 3.22)",
              "Do Provedor A": "10.200.11.20 / fd00:11::20", "Do Provedor B": "10.200.12.20 / fd00:12::20",
              "Papel RFC 9234": "provider (seleciona o algoritmo upstream)", "Config": "openbgpd/observer2-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer2", "bgpctl"], ["Shell", "observer2"]],
      hint: "bgpctl show sets\nbgpctl show rib detail\ncat /var/db/rpki-client/openbgpd\nrpki-refresh",
      edit: EDIT.observer2,
    },
    observer3: {
      name: "observador 3 — AS64511 (OpenBGPD + FORT)",
      role: "Outra opinião: mesmo prefixo, mesmos caminhos, outro roteador e outro validador, que entrega os dados pelo RTR. O OpenBGPD calcula os vereditos nativamente nos campos ovs e avs, sem precisar de communities.",
      info: { "ASN": "64511 (RFC 5398)", "Validador": "FORT (172.30.0.50:3323)", "Imagem": "OpenBGPD 8.8 (Alpine 3.22)",
              "Do Provedor A": "10.200.5.20 / fd00:5::20", "Do Provedor B": "10.200.6.20 / fd00:6::20",
              "Papel RFC 9234": "provider (seleciona o algoritmo upstream)", "Config": "openbgpd/observer3-<stage>.conf" },
      term: [["Terminal (bgpctl)", "observer3", "bgpctl"], ["Shell", "observer3"]],
      hint: "bgpctl show rib detail\nbgpctl show rtr\nbgpctl show sets",
      edit: EDIT.observer3,
    },
    registry_local: {
      role: "O RIR/NIR simulado que roda dentro do laboratório. Emite o certificado dos recursos alocados e hospeda o repositório. Sem Internet, sem credenciais.",
      info: { "Modo": "local (autocontido)", "Painel do registro": REGISTRY_URL,
              "Âncora de confiança": "gerada pelo próprio laboratório", "Publicação": "RRDP em https://rir.lab:3000/rrdp/" },
      hint: "krillc list\nkrillc children connections --ca testbed\nkrillc pubserver publishers list",
    },
    registry_beta: {
      role: "O sistema de testes do Registro.br: âncora de confiança, CA pai do seu AS e servidor de publicação remota. Precisa de Internet e de um login no beta.registro.br.",
      info: { "Modo": "beta (Registro.br)", "TAL": "https://rpki-test-ta.beta.registro.br/ta/ta.tal", "Painel": REGISTRO_BR_URL },
    },
  },
};
