#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The lab-aspa authors
# Translates lab.conf into the per-router parameter files:
#
#   bird/vars.conf       "define" statements, included by the BIRD routers
#   openbgpd/vars.conf   macros, included by observer2's OpenBGPD configs
#   guide/GUIDE.*.md     the guide, compiled from guide/templates/: every
#                        {{NAME}} marker becomes the value of NAME in lab.conf
#
# It's called automatically by ./scripts/lab.sh up.
set -euo pipefail
cd "$(dirname "$0")/.."

# shellcheck source=../lab.conf
. ./lab.conf
LANGUAGE="${LANGUAGE:-pt}"
. ./scripts/i18n.sh

cat > bird/vars.conf <<EOF
# ==============================================================================
# GENERATED by scripts/generate-config.sh from lab.conf - do not edit by hand.
# ==============================================================================
define ORIGIN_ASN       = ${ORIGIN_ASN};
define ORIGIN_V4        = ${ORIGIN_V4};
define ORIGIN_V4_MAXLEN = ${ORIGIN_V4_MAXLEN};
define ORIGIN_V6        = ${ORIGIN_V6};
define ORIGIN_V6_MAXLEN = ${ORIGIN_V6_MAXLEN};

define PROVIDER_A_ASN  = ${PROVIDER_A_ASN};
define PROVIDER_B_ASN  = ${PROVIDER_B_ASN};
define OBSERVER1_ASN   = ${OBSERVER1_ASN};
define OBSERVER2_ASN   = ${OBSERVER2_ASN};
define ATTACKER_ASN    = ${ATTACKER_ASN};
define PEER_ASN        = ${PEER_ASN};
EOF

cat > openbgpd/vars.conf <<EOF
# ==============================================================================
# GENERATED by scripts/generate-config.sh from lab.conf - do not edit by hand.
# OpenBGPD macros, included by the observer2 configurations.
# ==============================================================================
origin_asn="${ORIGIN_ASN}"
provider_a_asn="${PROVIDER_A_ASN}"
provider_b_asn="${PROVIDER_B_ASN}"
observer2_asn="${OBSERVER2_ASN}"
attacker_asn="${ATTACKER_ASN}"
EOF

echo "$(msg vars_generated) AS${ORIGIN_ASN}, ${ORIGIN_V4}, ${ORIGIN_V6}"

# ----------------------------------------------------------- the guide ----
# guide/templates/ holds the sources, with {{NAME}} markers (NAME = any
# variable in lab.conf); guide/GUIDE.*.md is what the panel serves.
sedargs=()
for name in $(sed -n 's/^\([A-Z][A-Z0-9_]*\)=.*/\1/p' lab.conf); do
    value="${!name}"
    value="${value//\\/\\\\}"; value="${value//&/\\&}"; value="${value//|/\\|}"
    sedargs+=(-e "s|{{${name}}}|${value}|g")
done
for tpl in guide/templates/GUIDE.*.md; do
    out="guide/$(basename "$tpl")"
    sed "${sedargs[@]}" "$tpl" > "$out"
    if grep -n '{{[A-Z0-9_]*}}' "$out" >&2; then
        echo "generate-config.sh: unresolved marker(s) in $tpl (see above)" >&2
        exit 1
    fi
done
