# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The lab-aspa authors
# Krill for the student's CA. Same as what the image generates by default,
# except "ip": "::" listens on IPv6 and IPv4 both (dual stack), so the panel's
# links work whether the browser resolves localhost to 127.0.0.1 or to ::1.
ip        = "::"
port      = 3000
data_dir  = "/var/krill/data"
log_type  = "stderr"
log_level = "info"
service_uri = "https://localhost:3000/"
